### ISSUE TITLE
date fields formats 

### ISSUE THREAD

**Issue by srendon-d** [vanna-ai/vanna-flask#5]
When I work with databases that have dates in YYYY-MM-DD format the calculations and queries are performed correctly, but when the dataframe is displayed or rendered the date format is displayed in a UNIX format, how can I display the dates in the normal format that is present in the database? 
![image](https://github.com/vanna-ai/vanna-flask/assets/88735092/88e69d27-dfe4-451d-be35-9666c5fd1fcf)
thanks

**Comment by akhilvk** [comment]
Check new changes committed to https://github.com/vanna-ai/vanna/tree/app-upgrades. this solved my issue.

**Comment by zainhoda** [comment]
This is now updated in v0.3.0
